# Borrowed from https://github.community/t/can-github-actions-directly-edit-files-in-a-repository/17884/6
# This is a basic workflow to help you get started with Actions

name: Build dmm.js Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'web/source.js'
    branches: ['development']


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'development'
    # Runs commands using the runners shell
    - name: Install libraries
      run: npm install
      working-directory: ./web
    - name: Run the build dmm.js script
      run: ./node_modules/.bin/browserify source.js -o dmm.js
      working-directory: ./web
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "GitHub Action"
        git add -f ./web/dmm.js
        git commit -m "Automated update of dmm.js"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.token }}
        branch: development

